#undef RF230_CONF_AUTOACK
#define RF230_CONF_AUTOACK 0
#undef RF230_CONF_FRAME_RETRIES
#define RF230_CONF_FRAME_RETRIES 0
#undef NODE_ID
 #define NODE_ID 5
// #undef RADIO_TX_POWER
// #define RADIO_TX_POWER 30
