# Test suite
suite:
    logbase:   log/
    logpattern: date-tag
    contikibase: ../
    contikiscm: none # Here only git and none are supported at the moment
    #workdir: /foo/bar
    testdirs:
        - . 
    testcases:
        - forward-test 

