# RIME unicast test
rime-unicast-sender: rime_unicast_sender
	
rime-unicast-receiver: rime_unicast_receiver
	

# RIME broadcast test

TARGET=inga

APPS = settings_set  

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
