# Accelerometer tests
acc-test: acc-test.c

# Gyroscope tests
gyro-test: gyro-test.c

# Battery tests
battery-test: battery-test.c
	
# Pressure and temperature tests
temppress-test: temppress-test.c


PROJECT_SOURCEFILES += sensor-tests.c ../test.c

TARGET=inga

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
