CONTIKI_PROJECT = default_app
all: $(CONTIKI_PROJECT)
CFLAGS += -DWITH_NODE_ID=1
#UIP_CONF_IPV6=1
ifdef NODE_ID
	CFLAGS +=-DNODEID=$(NODE_ID)
endif
#INGA_BAUDRATE = 38400
FAT=1
TARGET=inga
CFLAGS += -DCONFIG_GROUPS=10
CONTIKI_SOURCEFILES += ini_parser.c app_config.c

CONTIKI = ../..
include $(CONTIKI)/Makefile.include
