# FAT tests
fat-test: fat-test.c

# FAT coop tests
fat-coop-test: fat-coop-test.c


PROJECT_SOURCEFILES += ../sensor-tests.c

FAT=1
TARGET=inga

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
