# FAT tests
fat-tests: fat-tests.c

# FAT coop tests
fat-coop-tests: fat-coop-tests.c


#PROJECT_SOURCEFILES += ../sensor-tests.c

FAT=1
TARGET=inga

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
