tests:
### RIME stack test
  - name: inga-hardware-tests 
    timeout: 120
    devices:
      - name: receiver
        programdir: inga-hardware-tests
        program: hardware_tests_candidate
        instrument: []
        debug: []
        cflags: "-fno-inline -DNODE_CONF_ID=0x02 "
        graph_options: ""
      - name: sender
        programdir: inga-hardware-tests
        program: hardware_tests_reference
        instrument: []
        debug: []
        cflags: "-fno-inline -DNODE_CONF_ID=0x1 "
        graph_options: ""
