CONTIKI_PROJECT = run-tests
all: $(CONTIKI_PROJECT)

PROJECT_SOURCEFILES += fat-test.c acc-test.c gyro-test.c battery-test.c

TARGET=inga
FAT=1
#COFFEE_FILES=5

CONTIKI = ../..
include $(CONTIKI)/Makefile.include
