EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
hello-world/avr-raven \
hello-world/exp5438 \
hello-world/inga \
hello-world/minimal-net \
hello-world/native \
hello-world/sky \
hello-world/wismote \
hello-world/z1 \
eeprom-test/native \
collect/sky \
er-rest-example/sky \
er-rest-example/inga \
example-shell/native \
inga/demo/inga \
inga/sensors/inga \
inga/fat/inga \
rime/inga \
rime/sky \
ravenusbstick/avr-ravenusb \
rest-example/sky \
servreg-hack/inga \
servreg-hack/sky \
sky/sky \
sky-ip/sky \
webserver/minimal-net \
wget/minimal-net \
z1/z1 \
settings-example/avr-raven \
settings-example/inga \
ipv6/multicast/sky \
ipv6/multicast/inga

TOOLS=

include ../Makefile.compile-test
