CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

CONTIKI_PROJECT = dtnpingsender
all: $(CONTIKI_PROJECT)

DTN_APPS += dtnpingecho

CONTIKI_WITH_DTN=1

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
