/**
 * \addtogroup bprocess
 * @{
 */

/**
 * \file
 * \brief DTN App Support file
 * \author Wolf-Bastian Pšttner <poettner@ibr.cs.tu-bs.de>
 */

#include <string.h>
#include <stdio.h>

#include "contiki.h"
#include "logging.h"

#include "agent.h"
#include "dtn_apps.h"

/* This include only works if DTN_APPS are enabled */
#ifdef DTN_APPS_LIST
#include "dtn_apps_includes.h" /* This file is generated by Makefile.dtn at compile time */
#else
#define DTN_APPS_LIST {NULL}
#endif

const struct dtn_app * dtn_apps[] = DTN_APPS_LIST;

void dtn_apps_start()
{
	int h = 0;

	for(h=0; dtn_apps[h] != NULL; h++) {
		LOG(LOGD_DTN, LOG_AGENT, LOGL_INF, "Starting DTN App %s", dtn_apps[h]->name);
		dtn_apps[h]->init();
	}
}

/** @} */
