PROJECT_SOURCEFILES += sensor-tests.c
# RIME unicast test
hardware_tests_candidate: hardware_tests_candidate 
	
hardware_tests_reference: hardware_tests_reference 
	

# RIME broadcast test

TARGET=inga

CONTIKI = ../
include $(CONTIKI)/Makefile.include
