CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = uDTN-generate-bundles
all: $(CONTIKI_PROJECT)

#UIP_CONF_IPV6=1

CONTIKI_WITH_DTN=1
CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
